# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\srcdata\pyqt\college_wish\Select_MAJOR.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(790, 385)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(790, 385))
        Dialog.setMaximumSize(QtCore.QSize(790, 385))
        Dialog.setSizeGripEnabled(True)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 771, 311))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 700))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(700, 700))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.checkBox1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox1.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox1.setObjectName("checkBox1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox1)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.checkBox2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox2.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox2.setObjectName("checkBox2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox2)
        self.checkBox3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox3.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox3.setObjectName("checkBox3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox3)
        self.checkBox4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox4.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox4.setObjectName("checkBox4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox4)
        self.checkBox5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox5.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox5.setObjectName("checkBox5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox5)
        self.checkBox6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox6.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox6.setObjectName("checkBox6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBox6)
        self.checkBox7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox7.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox7.setObjectName("checkBox7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox7)
        self.checkBox8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox8.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox8.setObjectName("checkBox8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkBox8)
        self.checkBox9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox9.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox9.setObjectName("checkBox9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox9)
        self.checkBox10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox10.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox10.setObjectName("checkBox10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.checkBox10)
        self.checkBox11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox11.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox11.setObjectName("checkBox11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.checkBox11)
        self.checkBox12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox12.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox12.setObjectName("checkBox12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.checkBox12)
        self.checkBox13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox13.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox13.setObjectName("checkBox13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.checkBox13)
        self.checkBox14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox14.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox14.setObjectName("checkBox14")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.checkBox14)
        self.checkBox15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox15.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox15.setObjectName("checkBox15")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.checkBox15)
        self.checkBox16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox16.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox16.setObjectName("checkBox16")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.checkBox16)
        self.checkBox17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox17.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox17.setObjectName("checkBox17")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.checkBox17)
        self.checkBox18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox18.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox18.setObjectName("checkBox18")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.checkBox18)
        self.checkBox19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox19.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox19.setObjectName("checkBox19")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.checkBox19)
        self.checkBox20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox20.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox20.setObjectName("checkBox20")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.checkBox20)
        self.checkBox21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox21.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox21.setObjectName("checkBox21")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.checkBox21)
        self.checkBox22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox22.setMinimumSize(QtCore.QSize(0, 22))
        self.checkBox22.setObjectName("checkBox22")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.checkBox22)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEdit_17)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEdit_35)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.lineEdit_36)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.lineEdit_37)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.lineEdit_38)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.lineEdit_39)
        self.verticalLayout.addLayout(self.formLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(200, 340, 93, 28))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(440, 340, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择专业"))
        self.checkBox1.setText(_translate("Dialog", "计算机类"))
        self.lineEdit.setText(_translate("Dialog", "计算机科学与技术, 软件工程, 网络工程, 物联网工程"))
        self.checkBox2.setText(_translate("Dialog", "经济类"))
        self.checkBox3.setText(_translate("Dialog", "土木类"))
        self.checkBox4.setText(_translate("Dialog", "材料类"))
        self.checkBox5.setText(_translate("Dialog", "机械类"))
        self.checkBox6.setText(_translate("Dialog", "电气类"))
        self.checkBox7.setText(_translate("Dialog", "金融类"))
        self.checkBox8.setText(_translate("Dialog", "电子信息类"))
        self.checkBox9.setText(_translate("Dialog", "建筑类"))
        self.checkBox10.setText(_translate("Dialog", "矿业类"))
        self.checkBox11.setText(_translate("Dialog", "航空航天类"))
        self.checkBox12.setText(_translate("Dialog", "自动化类"))
        self.checkBox13.setText(_translate("Dialog", "工商管理类"))
        self.checkBox14.setText(_translate("Dialog", "设计学类"))
        self.checkBox15.setText(_translate("Dialog", "旅游管理类"))
        self.checkBox16.setText(_translate("Dialog", "数学类"))
        self.checkBox17.setText(_translate("Dialog", "物理类"))
        self.checkBox18.setText(_translate("Dialog", "化学类"))
        self.checkBox19.setText(_translate("Dialog", "生物科学类"))
        self.checkBox20.setText(_translate("Dialog", "历史学类"))
        self.checkBox21.setText(_translate("Dialog", "中国语言类"))
        self.checkBox22.setText(_translate("Dialog", "外国语言类"))
        self.lineEdit_2.setText(_translate("Dialog", "经济学, 财政学, 国民经济管理, 资源与环境经济学, 经济统计学"))
        self.lineEdit_3.setText(_translate("Dialog", "土木工程, 道路桥梁与渡河工程, 建筑环境与能源应用工程, 建筑电气与智能化, 铁道工程"))
        self.lineEdit_4.setText(_translate("Dialog", "材料科学与工程, 冶金工程, 高分子材料与工程, 金属材料工程, 无机非金属材料工程"))
        self.lineEdit_5.setText(_translate("Dialog", "机械工程, 机械设计制造及其自动化, 材料成型及控制工程, 工业设计, 车辆工程"))
        self.lineEdit_6.setText(_translate("Dialog", "电气工程及其自动化, 智能电网信息工程, 电气工程与智能控制, 光源与照明"))
        self.lineEdit_7.setText(_translate("Dialog", "金融学, 保险学, 金融数学, 投资学, 金融工程"))
        self.lineEdit_8.setText(_translate("Dialog", "通信工程, 电子信息工程, 电子科学与技术, 微电子科学与工程, 信息工程"))
        self.lineEdit_9.setText(_translate("Dialog", "建筑学, 城乡规划, 风景园林, 历史建筑保护工程"))
        self.lineEdit_10.setText(_translate("Dialog", "采矿工程, 石油工程, 矿物加工工程, 油气储运工程, 海洋油气工程"))
        self.lineEdit_11.setText(_translate("Dialog", "航空航天工程, 飞行器设计与工程, 飞行器制造工程, 飞行器动力工程, 飞行器适航技术"))
        self.lineEdit_12.setText(_translate("Dialog", "自动化, 轨道交通信号与控制"))
        self.lineEdit_13.setText(_translate("Dialog", "工商管理, 会计学, 财务管理, 审计学, 资产评估"))
        self.lineEdit_14.setText(_translate("Dialog", "艺术设计学, 视觉传达设计, 产品设计, 数字媒体艺术, 服装与服饰设计"))
        self.lineEdit_15.setText(_translate("Dialog", "旅游管理, 酒店管理, 会展经济与管理, 旅游管理与服务教育"))
        self.lineEdit_16.setText(_translate("Dialog", "数学与应用数学, 信息与计算科学, 数学"))
        self.lineEdit_17.setText(_translate("Dialog", "物理学, 应用物理学, 核物理, 物理"))
        self.lineEdit_35.setText(_translate("Dialog", "应用化学, 化学生物学, 分子科学与工程, 化学"))
        self.lineEdit_36.setText(_translate("Dialog", "生物科学, 生物技术, 生物信息学, 生态学, 生物"))
        self.lineEdit_37.setText(_translate("Dialog", "历史学, 世界史, 考古学, 文物保护技术, 历史"))
        self.lineEdit_38.setText(_translate("Dialog", "汉语言文学, 汉语言, 汉语国际教育, 古典文献学, 语言文学"))
        self.lineEdit_39.setText(_translate("Dialog", "英语, 俄语, 法语, 德语, 西班牙语, 阿拉伯语"))
        self.pushButton_ok.setText(_translate("Dialog", "确定"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

